# paasta-cubrid-service 설정 파일 내용
---
name: paasta-cubrid-service  # 서비스 배포이름(필수)

releases:
- name: paasta-cubrid  #서비스 릴리즈 이름(필수)
  version: "2.0"   #서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

update:
  canaries: 1                                          # canary 인스턴스 수(필수)
  canary_watch_time: 30000-180000                      # canary 인스턴스가 수행하기 위한 대기 시간(필수)
  max_in_flight: 6                                     # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 30000-180000                      # non-canary 인스턴스가 수행하기 위한 대기 시간(필수)

instance_groups:
- name: cubrid  #작업 이름(필수): Cubrid 서버
  azs:
  - z1
  instances: 1                               # job 인스턴스 수(필수)
  vm_type: ((vm_type_default))                 # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))           # cloud config 에 정의한 network 이름
    static_ips:
    - 10.244.0.160                          # 사용할 IP addresses 정의(필수): Cubrid 서버 IP
  templates:
  - name: cubrid
    release: paasta-cubrid
  env:
    bosh: 
      password: $6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0

- name: cubrid_broker   #작업 이름(필수): Cubrid 서비스 브로커
  azs:
  - z1
  instances: 1                               # job 인스턴스 수(필수)
  vm_type: ((vm_type_small))                 # cloud config 에 정의한 vm_type
  stemcell: default
  networks:
  - name: ((default_network_name))           # cloud config 에 정의한 network 이름
    static_ips:
    - 10.30.107.122                          # 사용할 IP addresses 정의(필수): broker IP
  templates:
  - name: cubrid_broker  # job template 이름(필수)
    release: paasta-cubrid

- name: cubrid_broker_registrar
  azs:
  - z1
  instances: 1
  lifecycle: errand
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
  properties:
      broker: # 서비스 브로커 설정 정보
        host: 10.244.0.161 # 서비스 브로커 IP 
        name: CubridDB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
        protocol: http
        port: 8088  # 브로커 포트
      cf:
        admin_password: admin   # CF 사용자의 패스워드
        admin_username: admin   # CF 사용자 이름
        api_url: https://api.bosh-lite.com   # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: cubrid_broker_registrar  # job template 이름(필수)
    release: paasta-cubrid

- name: cubrid_broker_deregistrar
  azs:
  - z1
  instances: 1 
  lifecycle: errand
  vm_type: ((vm_type_small))
  stemcell: default
  networks:
  - name: ((default_network_name))
  properties:
      broker: # 서비스 브로커 설정 정보
        host: 10.244.0.161 # 서비스 브로커 IP 
        name: CubridDB  # CF에서 서비스 브로커를 생성시 생기는 서비스 이름 브로커에 고정되어있는 값
        password: cloudfoundry  # 브로커 접근 아이디 비밀번호(필수)
        username: admin   # 브로커 접근 아이디(필수)
      cf:
        admin_password: admin   # CF 사용자의 패스워드
        admin_username: admin_test   # CF 사용자 이름
        api_url: https://api.bosh-lite.com   # CF 설치시 설정한 api uri 정보(필수)
  templates:
  - name: cubrid_broker_deregistrar  # job template 이름(필수)
    release: paasta-cubrid

properties:
  cubrid:   # Cubrid 설정 정보
    max_clients: 200
  cubrid_broker:  # Cubrid Servcice Broker 설정 정보
    cubrid_ip: 10.244.0.160 # Cubrid IP
    cubrid_db_port: 30000 # Cubrid Port
    cubrid_db_name: cubrid_broker   # Cubrid service 관리를 위한 데이터베이스 이름
    cubrid_db_user: dba   # 브로커 관리용 데이터베이스 접근 사용자이름
    cubrid_db_passwd: paasta  # 브로커 관리용 데이터베이스 접근 사용자 비밀번호
    cubrid_ssh_port: 22   # Cubrid가 설치된 서버 SSH 접속 포트
    cubrid_ssh_user: vcap # Cubrid가 설치된 서버 SSH 접속 사용자 이름
    cubrid_ssh_passwd: c1oudc0w # Cubrid가 설치된 서버 SSH 접속 사용자 비밀번호cubrid job의 bosh password 값
    cubrid_ssh_sudo_passwd: c1oudc0w # Cubrid가 설치된 서버 sudo 비밀번호cubrid job의 bosh password 값
    cubrid_ssh_identity: "" # Cubrid가 설치된 서버 SSH 접속 인증 키/var/vcap/jobs/cubrid_broker/config/bosh.pem 인증키 사용시
    #cubrid_ssh_identity: /var/vcap/jobs/cubrid_broker/config/bosh.pem # Cubrid가 설치된 서버 SSH 접속 >인증 키/var/vcap/jobs/cubrid_broker/config/bosh.pem
    cubrid_ssh_key: ""
#    cubrid_ssh_key: |
#      -----BEGIN RSA PRIVATE KEY-----
#      MIIEpAIBAAKCAQEA6Bf5unjJSccNlQk3jXqz4TNdpZkleKc92P69d1w//3moCyHz
#      RxZ9+FKaYgoJEmm7ydP4uEBA7Zpb6+SUyHGp3yv57PaeSgccyoci1tcgHg9XtVAH
#      c9wguyWwg8NDHNdX10Gsk8HRBtdK5CJLpIn3Wq0aiDndaCD2rrtRCqtCOHeTJy7q
#      N5bvnCBmaFeTKfZ7lIcasDwh8ynfDdmI6T38hXUAW50SF1A8JVfeq5xx0zt4Amgx
#      XeYduXFo7an6oYsJdqTOeYSuf+nswvgbSz1pKgnc0taxP9DLQRB+gJ1N/6xNjqhJ
#      4zNWRG4Dn2W84XDwwhZFMwXMXm5uqI16UxZZCwIDAQABAoIBAQDVKF/lENXdeoFQ
#      5Zwtxgm6xNA3LMYrX33/80XTf9gPLI5XWyDxowiirkq3y/u0+4LKxHFj1y9KiT/v
#      EIpM5YdcPilVptKNrqaUozQuGHmY4gJttUiC8iLlfqH1Abp7nJNCUUDMm278V3Ki
#      v5S1UzjoAJ+jiXF9Fvk4VTUDFXLGI9weF4wuxrF/d9f95TEEJ81U152lJY71M0km
#      v4cvc+G9IkeeBSCj0pwgUi/fMMXJaJuS93k/10QrISYiAo7ZoI6labE6+TCBag17
#      yFhm077Jms0suQ9tJjJMECcUQPefn3UtR/iBN/ar5pP1ADCR1u2HDA67u++QFLpr
#      FdSVjCuBAoGBAPjgUT9UOjPWAE3mXwb2pqjeumbaLGm/D0ihx+VvmmVxfG+7hz3h
#      Odkeq0Bo/u/k6XI99ai7T6GXY5eINcL+XMxEn/NNkgnfRcIiGyx2pwdRvlQv7Wao
#      znSgyB71tPG4yjwZjkAQG5suoRoHEngSWqbwjwYlMrFbupZ0SNlfdYgrAoGBAO68
#      rk+uYXQQdy+/j4hF9FA+rAktd8/W7qi4IVVJ57RNOjj9vM6ENqBT5N7EUWwTxbsZ
#      m+ZAPBQxEhdfnZsVvSDaKdkER9zEZCtIuHCQo0EHrWwKNkPecoxx6ZTibgWg0zrJ
#      cBCBa7kyg0GWRB7ngKevyQKbwm+bSf0jxes5QiKhAoGBALVq5y7v2gGBRPWEMc8k
#      qzY8LcrdzTREdwKuE8Y3BWhfQqM8IwjDjmSsC4/HOddrmZSSf+nAqPqVHZ8PRole
#      3Ax3FdXIvOT/YZ1zOTW/RGB8gO5jhX2pHd48ecS/vWfbGWiYBG7Ejyse4YbUkuz+
#      DCDXCJslMH/C6w/TsmrqQAXDAoGAT34oFIQeEwWAijeg1WFlrmqP4iZvpJcOtMNK
#      5hlLu6+TWXKzsZg4kD4fEUYRTolu55PpY0u0NYz5VysRUZh1d0DtekOAojQKnpcC
#      QwkGMxsZVcY4t3SUc8tiWZ7jv6ADdampVPWjJvF43xfn6tpu7mcL6YBvx7XPdyi4
#      OFDCgsECgYAYN2AZymeW9s4Noo8rM7KfMO00AupN5VgrJjFKKqRHT+trSjbhreQF
#      TXMm7JczHYurUaNuSxh14T1Wno5ybrKyRWKhuF9Og1B/ciUEUijifg6Vz+GFfR92
#      dvXLLjmsTzJ0dGO3vlEKwja9kyy2rN72gS/jLp1OeFReyf29cUD+Yw==
#      -----END RSA PRIVATE KEY----- 
